In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import tensorflow.keras.utils as utils
import matplotlib.pyplot as plt

In [2]:
# 1. 데이터 셋 생성
#raw_data = pd.read_excel('E:/kim_jiwon/note/09_ML_DL/data/heart-disease.xlsx')
raw_data = pd.read_csv('E:/kim_jiwon/note/09_ML_DL/data/winequality-red.csv',sep=';')
raw_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [4]:
raw_data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
raw_data.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
raw_data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
#종속변수분할
Input=raw_data.iloc[:,:-1]
Target=raw_data.iloc[:,[-1]] 
Target

      quality
0           5
1           5
2           5
3           6
4           5
...       ...
1594        5
1595        6
1596        6
1597        5
1598        6

[1599 rows x 1 columns]

In [8]:
#스케일 조절
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(Input)
scaled_input=scaler.transform(Input)
scaled_input=pd.DataFrame(scaled_input)
scaled_input

,0,1,2,3,4,5,6,7,8,9,10
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246
...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,1.542054,-0.075043,-0.978765,0.899886,-0.461180,0.072294
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,2.211469,0.137820,-0.862162,1.353436,0.601055,0.729364
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,1.255161,-0.196679,-0.533554,0.705508,0.542042,0.541630
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,1.542054,-0.075043,-0.676657,1.677400,0.305990,-0.209308
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,0.203223,-0.135861,-0.666057,0.511130,0.010924,0.541630

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(scaled_input,Target,test_size=0.3,random_state=5)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(1119, 11) (480, 11) (1119, 1) (480, 1)

In [10]:
#원핫
Y_train = utils.to_categorical(Y_train)
Y_test  = utils.to_categorical(Y_test)
Y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [17]:
# 모델 구성
model = Sequential()
model.add(Dense(units=50,input_dim=11,activation='relu'))
#과적합을 해결하고자 기억하되 두루뭉실하게 기억하기
model.add(Dense(units=30,activation='relu'))
model.add(Dense(units=20,activation='relu'))
model.add(Dense(units=9,activation='softmax'))
#여러개로나오니까 softmax, 그리고 9종으로 분류되니 units=9 결과물이 9개 나온다는걸....흑
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 50)                600
_________________________________________________________________
dense_13 (Dense)             (None, 30)                1530
_________________________________________________________________
dense_14 (Dense)             (None, 20)                620
_________________________________________________________________
dense_15 (Dense)             (None, 9)                 189
=================================================================
Total params: 2,939
Trainable params: 2,939
Non-trainable params: 0
_________________________________________________________________

In [19]:
#학습과정설정
model.compile(loss='mse',optimizer='adam',metrics=['accuracy'])
#학습시키기
fit_hist = model.fit(X_train,Y_train,epochs=100,batch_size=50,verbose=2)

Epoch 1/100
23/23 - 1s - loss: 0.0284 - accuracy: 0.8517
Epoch 2/100
23/23 - 0s - loss: 0.0273 - accuracy: 0.8597
Epoch 3/100
23/23 - 0s - loss: 0.0276 - accuracy: 0.8606
Epoch 4/100
23/23 - 0s - loss: 0.0268 - accuracy: 0.8704
Epoch 5/100
23/23 - 0s - loss: 0.0267 - accuracy: 0.8633
Epoch 6/100
23/23 - 0s - loss: 0.0267 - accuracy: 0.8597
Epoch 7/100
23/23 - 0s - loss: 0.0264 - accuracy: 0.8695
Epoch 8/100
23/23 - 0s - loss: 0.0262 - accuracy: 0.8695
Epoch 9/100
23/23 - 0s - loss: 0.0272 - accuracy: 0.8615
Epoch 10/100
23/23 - 0s - loss: 0.0268 - accuracy: 0.8651
Epoch 11/100
23/23 - 0s - loss: 0.0258 - accuracy: 0.8704
Epoch 12/100
23/23 - 0s - loss: 0.0255 - accuracy: 0.8695
Epoch 13/100
23/23 - 0s - loss: 0.0256 - accuracy: 0.8749
Epoch 14/100
23/23 - 0s - loss: 0.0253 - accuracy: 0.8704
Epoch 15/100
23/23 - 0s - loss: 0.0255 - accuracy: 0.8686
Epoch 16/100
23/23 - 0s - loss: 0.0253 - accuracy: 0.8740
Epoch 17/100
23/23 - 0s - loss: 0.0247 - accuracy: 0.8794
Epoch 18/100
23/23 - 0s - loss: 0.0249 - accuracy: 0.8749
Epoch 19/100
23/23 - 0s - loss: 0.0246 - accuracy: 0.8740
Epoch 20/100
23/23 - 0s - loss: 0.0244 - accuracy: 0.8785
Epoch 21/100
23/23 - 0s - loss: 0.0245 - accuracy: 0.8776
Epoch 22/100
23/23 - 0s - loss: 0.0247 - accuracy: 0.8758
Epoch 23/100
23/23 - 0s - loss: 0.0240 - accuracy: 0.8811
Epoch 24/100
23/23 - 0s - loss: 0.0239 - accuracy: 0.8785
Epoch 25/100
23/23 - 0s - loss: 0.0235 - accuracy: 0.8856
Epoch 26/100
23/23 - 0s - loss: 0.0242 - accuracy: 0.8740
Epoch 27/100
23/23 - 0s - loss: 0.0238 - accuracy: 0.8847
Epoch 28/100
23/23 - 0s - loss: 0.0234 - accuracy: 0.8856
Epoch 29/100
23/23 - 0s - loss: 0.0232 - accuracy: 0.8820
Epoch 30/100
23/23 - 0s - loss: 0.0232 - accuracy: 0.8856
Epoch 31/100
23/23 - 0s - loss: 0.0229 - accuracy: 0.8856
Epoch 32/100
23/23 - 0s - loss: 0.0226 - accuracy: 0.8865
Epoch 33/100
23/23 - 0s - loss: 0.0231 - accuracy: 0.8829
Epoch 34/100
23/23 - 0s - loss: 0.0226 - accuracy: 0.8865
Epoch 35/100
23/23 - 0s - loss: 0.0229 - accuracy: 0.8892
Epoch 36/100
23/23 - 0s - loss: 0.0234 - accuracy: 0.8820
Epoch 37/100
23/23 - 0s - loss: 0.0227 - accuracy: 0.8865
Epoch 38/100
23/23 - 0s - loss: 0.0225 - accuracy: 0.8856
Epoch 39/100
23/23 - 0s - loss: 0.0223 - accuracy: 0.8892
Epoch 40/100
23/23 - 0s - loss: 0.0221 - accuracy: 0.8910
Epoch 41/100
23/23 - 0s - loss: 0.0218 - accuracy: 0.8945
Epoch 42/100
23/23 - 0s - loss: 0.0225 - accuracy: 0.8901
Epoch 43/100
23/23 - 0s - loss: 0.0228 - accuracy: 0.8874
Epoch 44/100
23/23 - 0s - loss: 0.0220 - accuracy: 0.8963
Epoch 45/100
23/23 - 0s - loss: 0.0220 - accuracy: 0.8954
Epoch 46/100
23/23 - 0s - loss: 0.0223 - accuracy: 0.8892
Epoch 47/100
23/23 - 0s - loss: 0.0215 - accuracy: 0.8963
Epoch 48/100
23/23 - 0s - loss: 0.0211 - accuracy: 0.8972
Epoch 49/100
23/23 - 0s - loss: 0.0210 - accuracy: 0.8963
Epoch 50/100
23/23 - 0s - loss: 0.0214 - accuracy: 0.8945
Epoch 51/100
23/23 - 0s - loss: 0.0209 - accuracy: 0.8990
Epoch 52/100
23/23 - 0s - loss: 0.0208 - accuracy: 0.8963
Epoch 53/100
23/23 - 0s - loss: 0.0212 - accuracy: 0.9026
Epoch 54/100
23/23 - 0s - loss: 0.0213 - accuracy: 0.8937
Epoch 55/100
23/23 - 0s - loss: 0.0212 - accuracy: 0.8981
Epoch 56/100
23/23 - 0s - loss: 0.0206 - accuracy: 0.8999
Epoch 57/100
23/23 - 0s - loss: 0.0205 - accuracy: 0.9008
Epoch 58/100
23/23 - 0s - loss: 0.0207 - accuracy: 0.8990
Epoch 59/100
23/23 - 0s - loss: 0.0203 - accuracy: 0.9035
Epoch 60/100
23/23 - 0s - loss: 0.0206 - accuracy: 0.8972
Epoch 61/100
23/23 - 0s - loss: 0.0209 - accuracy: 0.9008
Epoch 62/100
23/23 - 0s - loss: 0.0201 - accuracy: 0.9053
Epoch 63/100
23/23 - 0s - loss: 0.0197 - accuracy: 0.9080
Epoch 64/100
23/23 - 0s - loss: 0.0198 - accuracy: 0.9035
Epoch 65/100
23/23 - 0s - loss: 0.0198 - accuracy: 0.9035
Epoch 66/100
23/23 - 0s - loss: 0.0203 - accuracy: 0.8963
Epoch 67/100
23/23 - 0s - loss: 0.0196 - accuracy: 0.9053
Epoch 68/100
23/23 - 0s - loss: 0.0199 - accuracy: 0.9053
Epoch 69/100
23/23 - 0s - loss: 0.0196 - accuracy: 0.9071
Epoch 70/100
23/23 - 0s - loss: 0.0196 - accuracy: 0.9062
Epoch 71/100
23/23 - 0s - loss: 0.0195 - accuracy: 0.9071
Epoch 72/100
23/23 - 0s - loss: 0.0193 - accuracy: 0.9071
Epoch 73/100
23/23 - 0s - loss: 0.0197 - accuracy: 0.9080
Epoch 74/100
23/23 - 0s - loss: 0.0193 - accuracy: 0.9062
Epoch 75/100
23/23 - 0s - loss: 0.0189 - accuracy: 0.9097
Epoch 76/100
23/23 - 0s - loss: 0.0194 - accuracy: 0.9044
Epoch 77/100
23/23 - 0s - loss: 0.0187 - accuracy: 0.9080
Epoch 78/100
23/23 - 0s - loss: 0.0188 - accuracy: 0.9106
Epoch 79/100
23/23 - 0s - loss: 0.0192 - accuracy: 0.9035
Epoch 80/100
23/23 - 0s - loss: 0.0223 - accuracy: 0.8811
Epoch 81/100
23/23 - 0s - loss: 0.0199 - accuracy: 0.9044
Epoch 82/100
23/23 - 0s - loss: 0.0187 - accuracy: 0.9071
Epoch 83/100
23/23 - 0s - loss: 0.0183 - accuracy: 0.9088
Epoch 84/100
23/23 - 0s - loss: 0.0184 - accuracy: 0.9080
Epoch 85/100
23/23 - 0s - loss: 0.0183 - accuracy: 0.9106
Epoch 86/100
23/23 - 0s - loss: 0.0185 - accuracy: 0.9106
Epoch 87/100
23/23 - 0s - loss: 0.0179 - accuracy: 0.9160
Epoch 88/100
23/23 - 0s - loss: 0.0178 - accuracy: 0.9106
Epoch 89/100
23/23 - 0s - loss: 0.0178 - accuracy: 0.9124
Epoch 90/100
23/23 - 0s - loss: 0.0178 - accuracy: 0.9080
Epoch 91/100
23/23 - 0s - loss: 0.0176 - accuracy: 0.9142
Epoch 92/100
23/23 - 0s - loss: 0.0173 - accuracy: 0.9142
Epoch 93/100
23/23 - 0s - loss: 0.0175 - accuracy: 0.9142
Epoch 94/100
23/23 - 0s - loss: 0.0177 - accuracy: 0.9142
Epoch 95/100
23/23 - 0s - loss: 0.0176 - accuracy: 0.9124
Epoch 96/100
23/23 - 0s - loss: 0.0171 - accuracy: 0.9133
Epoch 97/100
23/23 - 0s - loss: 0.0171 - accuracy: 0.9133
Epoch 98/100
23/23 - 0s - loss: 0.0168 - accuracy: 0.9169
Epoch 99/100
23/23 - 0s - loss: 0.0167 - accuracy: 0.9169
Epoch 100/100
23/23 - 0s - loss: 0.0170 - accuracy: 0.9160

In [ ]:
# print(redwine_y.unique()) # 종류확인
redwind_y = pd.get-cummies(redwine_y).to_numpy() #알아서 unique해서 sort해서 만들어줌. 숫자 아니어도 ㅇㅋㅇㅋ